---
apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    name: flask-app
  namespace: flask-app
spec:
  containers:
    - name: flask-app
      image: koteikin/flask-app:4
      imagePullPolicy: Always
      command: ["python"]
      args: ["-m", "flask", "run"]
      env:
        - name: FLASK_APP
          value: api.py
        - name: FLASK_ENV
          value: development
        - name: DB_USERNAME
          value: user
        - name: DB_NAME
          value: db
        - name: DB_HOSTNAME
          value: db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
      resources:
        limits:
          memory: "256Mi"
          cpu: "300m"
        requests:
          memory: "256Mi"
          cpu: "200m"
      ports:
        - containerPort: 5000
          name: flask
      startupProbe:
        httpGet:
          path: /
          port: flask
        failureThreshold: 5
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: flask
        failureThreshold: 5
        periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-app
spec:
  selector:
    name: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: flask
      name: flask-svc
